home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('contact/update/<int:id>', views.contact_update, name="contact_update"),
    path('hero/create', views.hero_create, name='hearo_create'),
    path('hero/update/<int:id>', views.hero_update, name='hearo_update'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.utils import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story/', include('story.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

# active virtual env: source /venv/bin/activate
# (venv)....$
# to run server: python manage.py runserver <0:8000>

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

home/models.py
from django.db import models
# from django.conf import settings
# from django.utils.text import slugify
# from django.db.models.signals import pre_save
# from django.urls import reverse
# Create your models here.


class Article(models.Model):
    title = models.CharField(max_length=100, unique=True)
    image = models.ImageField(upload_to='article/',
                              default='default.jpg', blank=True, null=True)
    date = models.DateTimeField()
    content = models.TextField()
    draft = models.BooleanField(default=True)

    def __str__(self):
        return self.title


class Hero(models.Model):
    image = models.ImageField(upload_to='hero/', default='default.jpg')
    caption = models.CharField(max_length=250)
    sub_heading = models.CharField(max_length=150)
    date = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.caption


class Contact(models.Model):
    full_name = models.CharField("Full Name", max_length=80)
    email = models.EmailField("Email", max_length=254)
    address = models.CharField(max_length=150)
    phone_number = models.CharField(max_length=10)
    message = models.TextField()
    timestamp = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return self.full_name


# class Tag(models.Model):
#     name = models.CharField(max_length=100)

#     def __str__(self):
#         return self.name


# class Story(models.Model):
#     title = models.CharField(max_length=200)
#     slug = models.SlugField(unique=True, blank=True, null=True)
#     tag = models.ForeignKey(Tag, on_delete=models.CASCADE, default=None)
#     photographer = models.ForeignKey(
#         settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
#     image = models.ImageField(upload_to='story/', default='default.jpg')
#     date = models.DateTimeField()
#     content = models.TextField()
#     draft = models.BooleanField(default=True)

#     def __str__(self):
#         return self.title

#     def get_absolute_url(self):
#         return reverse("home:storyDetail", kwargs={"slug": self.slug})

#     class Meta:
#         ordering = ["-date"]
#         verbose_name = "My Story"
#         verbose_name_plural = "My Stories"


# def create_slug(instance, new_slug=None):
#     slug = slugify(instance.title)
#     if new_slug is not None:
#         slug = new_slug

#     qs = Story.objects.filter(slug=slug).order_by("-id")
#     exists = qs.exists()
#     if exists:
#         new_slug = "%s-%s" % (slug, qs.first().id)
#         return create_slug(instance, new_slug=new_slug)
#     return slug


# def pre_save_post_receiver(sender, instance, *args, **kwargs):
#     instance.slug = create_slug(instance)
#     # do other stuffs here


# pre_save.connect(pre_save_post_receiver, sender=Story)

home/forms.py
from django import forms

from .models import Contact, Hero


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = ['full_name', 'email', 'address', 'phone_number', 'message']


class HeroForm(forms.ModelForm):
    class Meta:
        model = Hero
        fields = ['image', 'caption', 'sub_heading']

home/views.py
from django.shortcuts import render, get_object_or_404
# from django.http import HttpResponse
from .forms import ContactForm, HeroForm
from .models import Article, Hero, Contact
from django.contrib import messages
from django.contrib.auth.decorators import login_required
# Create your views here.


def contactFormHandle(request):
    received = 0
    if request.method == 'POST':
        received = 1
        print("Form Received")
        form = ContactForm(request.POST or None, request.FILES or None)
        if form.is_valid():
            form.save()
            messages.success(
                request, 'You have successfully submitted your message.')
        else:
            messages.error(
                request, 'Error submitting your message. Please correct errors and Try again.')
    context = {
        "form": ContactForm()
    }
    return context


def index(request):
    article_list = Article.objects.all()
    hero_list = Hero.objects.all()
    print(article_list)
    context = {
        "articles": article_list,
        "hero_list": hero_list
    }
    return render(request, 'home/index.html', context)
    # return HttpResponse("<h2>Hello, We have done it..</h2>")


# @login_required(login_url='admin/')
# def hero_create(request):


def contact(request):
    context = {
        # "form": contactFormHandle(request)
    }
    return render(request, 'home/contact.html', context)


@login_required(login_url='/admin/login/')
def hero_create(request):
    form = HeroForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(
                request, 'You have successfully created Hero Slider.')
        else:
            messages.error(
                request, 'Error creating hero slider. Please correct errors and Try again.')
    context = {
        "form": form
    }
    return render(request, 'home/hero_create.html', context)


@login_required(login_url='/admin/login/')
def hero_update(request, id=None):
    instance = get_object_or_404(Hero, id=id)
    form = HeroForm(request.POST or None,
                    request.FILES or None, instance=instance)
    print(form)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(
                request, 'You have successfully updated Hero Slider.')
        else:
            messages.error(
                request, 'Error updating hero slider. Please correct errors and Try again.')
    context = {
        "instance": instance,
        "form": form,
        "update": True
    }
    return render(request, 'home/hero_create.html', context)


@login_required(login_url='/admin/login/')
def contact_update(request, id=None):
    instance = get_object_or_404(Contact, id=id)
    form = ContactForm(request.POST or None,
                       request.FILES or None, instance=instance)
    if request.method == 'POST':
        if form.is_valid():
            form.save()
            messages.success(
                request, 'You have successfully updated your message.')
        else:
            messages.error(
                request, 'Error updating your message. Please correct errors and Try again.')

    context = {
        "instance": instance,
        "form": form
    }
    return render(request, 'home/contact.html', context)

templates/home/contact.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
Contact
{% endblock %}
{% block content %}

<div class="container my-4">
    <div class="row">
        <div class="col">
            <h3>Contact Form</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="" accept-charset="utf-8" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <img id="image-upload" src="" alt="">
                    <label for="full_name">Full Name</label>
                    <input type="text" value="{% if form.full_name.value %}{{form.full_name.value}}{% endif %}"
                        class="form-control" name="full_name" id="id_full_name" placeholder="Enter your full name">
                    <!-- <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone
                        else.</small> -->
                </div>
                <div class="form-group">
                    <label for="email">Email</label>
                    <input type="email" value="{% if form.email.value %}{{form.email.value}}{% endif %}"
                        class="form-control" name="email" id="id_email" placeholder="Enter your email address">
                </div>
                <div class="form-group">
                    <label for="phone_number">Phone Number</label>
                    <input type="number" value="{% if form.phone_number.value %}{{form.phone_number.value}}{% endif %}"
                        class="form-control" name="phone_number" id="id_phone_number"
                        placeholder="Enter your phone number">
                </div>
                <div class="form-group">
                    <label for="address">Address</label>
                    <input type="text" value="{% if form.address.value %}{{form.address.value}}{% endif %}"
                        class="form-control" name="address" id="id_address" placeholder="Enter your address">
                </div>
                <div class="form-group">
                    <label for="message">Message</label>
                    <textarea class="form-control" value="{% if form.message.value %}{{form.message.value}}{% endif %}"
                        name="message" id="id_message" rows="5"></textarea>
                </div>
                <button type="submit" class="btn btn-primary">Submit</button>
            </form>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary my-3" role="alert">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block script_links %}
{% endblock %}
{% block scripts %}

<script>
    $('#image-upload')
</script>
{% endblock %}

templates/home/hero_create.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
{% if update %} Hero-Update {% else %}Hero-Create{% endif %}
{% endblock %}
{% block content %}

<div class="container my-4">
    <div class="row">
        <div class="col">
            <h3>Create Hero Slider</h3>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <form method="POST" action="" accept-charset="utf-8" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    <label for="image">Image</label>
                    <input type="file" value="{% if form.image.value %}{{form.image.value}}{% endif %}"
                        class="form-control" name="image" id="id_image">
                </div>
                <div class="my-2 image-holder">
                    <img id="image_holder" src="{% if instance %}{{instance.image.url}} {%  endif %}"
                        style="height: 50px;" alt="{{instance.caption}}">
                </div>
                <div class="form-group">
                    <label for="caption">Caption</label>
                    <input type="text" value="{% if form.caption.value %}{{form.caption.value}}{% endif %}"
                        class="form-control" name="caption" id="id_caption" placeholder="Enter image caption">
                </div>
                <div class="form-group">
                    <label for="sub_heading">Sub Heading</label>
                    <input type="text" value="{% if form.sub_heading.value %}{{form.sub_heading.value}}{% endif %}"
                        class="form-control" name="sub_heading" id="id_sub_heading" placeholder="Enter Sub Heading">
                </div>
                <button type="submit" class="btn btn-primary">{% if update %}Update {% else %} Submit
                    {% endif %}</button>
            </form>
            {% if messages %}
            {% for message in messages %}
            <div class="alert alert-primary my-3" role="alert">
                {{message}}
            </div>
            {% endfor %}
            {% endif %}
        </div>
    </div>
</div>
{% endblock %}

{% block script_links %}
{% endblock %}
{% block scripts %}

<script>
    $(document).ready(function () {
        $('#id_image').on('change', function () {
            if (this.files && this.files[0]) {
                var reader = new FileReader();
                reader.onload = function (e) {
                    $('#image_holder').attr('src', e.target.result);
                }
                reader.readAsDataURL(this.files[0]);
            }
        })
    });
</script>
{% endblock %}

templates/home/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block meta_links %}
{% endblock %}
{% block style_links %}

{% endblock %}

{% block title %}
Home
{% endblock %}

{% block content %}
<div class="container">

</div>
{% endblock %}

{% block script_links %}
{% endblock %}
{% block scripts %}
{% endblock %}