home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('contact/update/<int:id>', views.contact_update, name="contact_update"),
    path('hero/create', views.hero_create, name='hearo_create'),
    path('hero/update/<int:id>', views.hero_update, name='hearo_update'),
]

story/urls.py
from django.urls import path

from . import views

app_name = 'story'

urlpatterns = [
    path('', views.story, name='story'),
    path('<slug:slug>/', views.story_detail, name='storyDetail'),
    path('tag/<str:name>', views.story_tag, name='tagStory'),
]

travel/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
# from django.utils import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('story/', include('story.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]

# active virtual env: source /venv/bin/activate
# (venv)....$
# to run server: python manage.py runserver <0:8000>

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    {% block meta_links %}
    {% endblock %}
    <!-- template tags -->
    {% load staticfiles %}
    <title>{% block title%}{% endblock %}</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    {% block style_links %}
    {% endblock %}
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">TravelBoss</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'story:story' %}">Story</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'home:contact' %}">Contact Me</a>
                </li>
            </ul>
        </div>
    </nav>

    {% block content  %}
    <!-- place footer component here -->

    {% endblock content %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous">
    </script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous">
    </script>
    {% block script_links %}

    {% endblock %}
    {% block scripts %}
    {% endblock %}

</body>

</html>